### ISSUE TITLE
[FEATURE REQUEST] Work Apps

### ISSUE THREAD

**Issue by 0xlne** [MrMannWood/launcher#6]
I have a work profile on my device & at this moment, Hex doesn't display the work apps.

**Comment by mhmdanas** [comment]
Copying over my issue body from #6, in case it's useful:

> I use [Shelter](https://github.com/PeterCxy/Shelter) to isolate some "Big Brother" apps from the other apps, and I can't seem to find apps in the work profile in Hex Launcher. Neither can I find them in Settings > Show All Apps, if that helps matters. I use Android 11 with a Samsung A51.
> Some links I found that might be useful: https://github.com/Neamar/KISS/issues/542 https://github.com/Neamar/KISS/pull/609

**Comment by MrMannWood** [comment]
I'm not familiar with work profiles at all, and Hex Launcher is a full re-implementation (e.g. not using the common library that most launchers use). If this is a "must have" feature for you, then you should look elsewhere for now. Sorry!

I will be looking at this as a long term task.

**Comment by 0xlne** [comment]
Thanks for your response; for what it's worth,it's been done in some of the other FOSS apps (Posidon, Kvaesitso, Lawnchair) so a look at their source might help on how to access the list of apps within that work profile.

**Comment by MrMannWood** [comment]
This should be supported as as 1.4.4. I don't have access to a device with a work profile, so it would be great it someone could confirm that this actually works properly.

**Comment by mhmdanas** [comment]
Unfortunately, on my device, the app crashes on launch with the following exception:
```
android.content.pm.PackageManager$NameNotFoundException: org.thoughtcrime.securesms
	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:292)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:264)
	at s2.d.b(Unknown Source:42)
	at s2.d.c(Unknown Source:159)
	at androidx.appcompat.widget.a1.run(:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

`org.thoughtcrime.securesms` is the application ID of Signal, which I have installed in my work profile but not in my main one.

**Comment by MrMannWood** [comment]
Thanks for the bug report! I'll try to push a fix this weekend.

**Comment by MrMannWood** [comment]
It looks like this is caused because you have Signal set as one of your shortcuts. The way I'm reading and setting up the shortcuts is causing signal to crash, likely because it's in your work profile.

As a quick fix, you could clear the app's data. This will reset all of your settings (sorry!) but will solve the crashing problem. You would also need to not set another work profile app as a shortcut until I've implemented a proper fix.

**Comment by mhmdanas** [comment]
Sorry, but I have no idea what you mean by setting Signal as one of my shortcuts. Also, clearing Hex Launcher's data (assuming that is what you mean by "app") doesn't fix the crash.

Sorry if I misunderstood something here.

**Comment by MrMannWood** [comment]
Nope, you've provided extremely valuable information.

**Comment by MrMannWood** [comment]
Should be fixed in 1.4.6. I don't have a work profile and can't confirm, but fingers are crossed. Reopen if crash continues.
